### ISSUE TITLE
error[E0597]: `src` does not live long enough

### ISSUE THREAD

**Issue by Joaqim** [Joaqim/vic3-parser-rust#1]
Introduced by 764fb8174f1aa9b2d6efa4e617f3330f615b4be9 for branch [feat/use-ordered-hash-map](/Joaqim/vic3-parser-rust/tree/feat/use-ordered-hash-map)

https://github.com/Joaqim/vic3-parser-rust/blob/764fb8174f1aa9b2d6efa4e617f3330f615b4be9/src/main.rs#L34

Lifetime fails when using OrderedHashMap without cloning `src`

```shell
error[E0597]: `src` does not live long enough
  --> src/main.rs:34:25
   |
31 |     let src = fs::read_to_string(&filename).expect("Failed to read file");
   |         --- binding `src` declared here
...
34 |     match parse_program(&src) {
   |           --------------^^^^-
   |           |             |
   |           |             borrowed value does not live long enough
   |           a temporary with access to the borrow is created here ...
...
66 | }
   | -
   | |
   | `src` dropped here while still borrowed
   | ... and the borrow might be used here, when that temporary is dropped and runs the destructor for type `std::result::Result<value::Value<'_>, (std::string::String, std::ops::Range<usize>)>`
   |
help: consider adding semicolon after the expression so its temporaries are dropped sooner, before the local variables declared by the block are dropped
   |
65 |     };
   |      +

error[E0505]: cannot move out of `src` because it is borrowed
  --> src/main.rs:62:50
   |
31 |     let src = fs::read_to_string(&filename).expect("Failed to read file");
   |         --- binding `src` declared here
...
34 |     match parse_program(&src) {
   |           -------------------
   |           |             |
   |           |             borrow of `src` occurs here
   |           a temporary with access to the borrow is created here ...
...
62 |                 .eprint((&filename, Source::from(src)))
   |                                                  ^^^ move out of `src` occurs here
...
66 | }
   | - ... and the borrow might be used here, when that temporary is dropped and runs the destructor for type `std::result::Result<value::Value<'_>, (std::string::String, std::ops::Range<usize>)>`
```
